### ISSUE TITLE
1.0.0 roadmap

### ISSUE THREAD

**Issue by benmerckx** [benmerckx/rado#11]
- [x] apply transaction options
- [ ] mark schema updates as experimental
- [x] rewrite readme
- [x] check index api to match
- [x] returning() without argument
- [x] query.toSQL()
- [x] transaction async return type wrapped twice in promise
- [x] notNull on default column should not result in requiredcolumn
